query BoardWithListsAndCards ($id: ID!){
    board(id:$id){
        id
        title
        color
        lists{
            id
            board_id
            board{
                owner_id
            }
            title
            cards{
                id
                title
                order
                owner_id
            }
        }
    }
}
