mutation ListAdd($title:String!, $board_id: ID!){
    listAdd(title:$title, board_id:$board_id){
        id
        board_id
        board{
            owner_id
        }
        title
        cards{
            id
            title
            order
            owner_id
        }
    }
}
